-- Adiciona novos campos à tabela de colaboradores
ALTER TABLE "collaborators" 
ADD COLUMN IF NOT EXISTS "hours_per_day" INTEGER DEFAULT 8,
ADD COLUMN IF NOT EXISTS "city" TEXT DEFAULT 'São Paulo',
ADD COLUMN IF NOT EXISTS "is_fixed" BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS "is_responsible" BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS "participates_in_stages" BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS "billable_type" TEXT DEFAULT 'hourly',
ADD COLUMN IF NOT EXISTS "observations" TEXT,
ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT NOW();